### ISSUE TITLE
Uncaught exception 'Slim\Exception\Stop'

### ISSUE THREAD

**Issue by plong0** [entomb/slim-json-api#20]
Hey, thanks for your tidy little API.  I just installed it into my app, but I am receiving this error when using the JsonApi middleware + view...

```
PHP Fatal error:  Uncaught exception 'Slim\Exception\Stop' in /.../vendor/slim/slim/Slim/Slim.php:1017
Stack trace:
#0 /.../vendor/entomb/slim-json-api/jsonAPI/JsonApiView.php(86): Slim\Slim->stop()
```

I am calling the view render from another middleware's call() function as:
```
$this->app->render(401, array(
        		'error' => TRUE,
        		'message' => 'Access denied.'
        		));
```

Wondering why this happens and where would be the proper place to catch the exception?

**Comment by entomb** [comment]
hey!

this was suposed to be catched by the Slim core (on the Slim\call() method) so that Slim echos the body immediately and stops any further transformations or callbacks (like trying to find a template or re-setting the content type)

I need to test if anything changed or if any server config might be doing this, meanwhile can you try using `$app->response()->write();` instead of `app->stop()` ?

**Comment by plong0** [comment]
Sorry for not updating earlier.  It seems to be happening when I echo/print anything before calling $app->render(), which I guess would interfere with the headers and would be my fault not Slim's or JsonApi ;)

**Comment by entomb** [comment]
Yeah, that might ruin the header assignment and output buffers too,
well, ok! thanks for the feedback!
